DROP DATABASE IF EXISTS `MERCADONA`;
CREATE DATABASE `MERCADONA`;

USE `MERCADONA`;

DROP TABLE IF EXISTS `DESTINO`;

CREATE TABLE `DESTINO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`)
);

INSERT INTO `DESTINO` (`ID`, `NOMBRE`)
VALUES
        (1,'MERCADONA_ESP'),
        (2,'MERCADONA_ESP'),
        (3,'MERCADONA_ESP'),
        (4,'MERCADONA_ESP'),
        (5,'MERCADONA_ESP'),
        (6,'MERCADONA_POR'),
        (8,'ALMACENES'),
        (9,'OFICINAS_MERCADONA'),
        (0,'COLMENAS');

DROP TABLE IF EXISTS `PROVEDOR`;

CREATE TABLE `PROVEDOR` (
  `CODIGO` BIGINT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`CODIGO`)
);

INSERT INTO `PROVEDOR` (`codigo`, `nombre`)
VALUES
    (8437008,'Hacendado'),
    (8480000,'Provedor Externo Prueba0');


DROP TABLE IF EXISTS `PRODUCTO`;

CREATE TABLE `PRODUCTO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CODIGO` BIGINT NOT NULL,
  `CODIGO_PROVEDOR` BIGINT NOT NULL,
  `ID_DESTINO` INT NOT NULL,
  `NOMBRE` VARCHAR(255) NOT NULL,
  `DESCRIPCION` VARCHAR(255) DEFAULT NULL,
  `FECHA_ALTA_REGISTRO` TIMESTAMP(6) NOT NULL,
  `FECHA_ULTIMA_MODIFICACION` TIMESTAMP(6) NULL DEFAULT NULL,
  `FECHA_BAJA_PRODUCTO` TIMESTAMP(6) NULL DEFAULT NULL,
   PRIMARY KEY (`ID`),
   CONSTRAINT `FK_CODIGO_PROVEDOR`FOREIGN KEY (`CODIGO_PROVEDOR`) REFERENCES `PROVEDOR` (`CODIGO`),
   CONSTRAINT `FK_ID_DESTINO`FOREIGN KEY (`ID_DESTINO`) REFERENCES `DESTINO` (`ID`)
);


INSERT INTO `PRODUCTO` (`ID`, `CODIGO`, `CODIGO_PROVEDOR`, `ID_DESTINO`, `NOMBRE`, `DESCRIPCION`, `FECHA_ALTA_REGISTRO`, `FECHA_ULTIMA_MODIFICACION`, `FECHA_BAJA_PRODUCTO`)
VALUES
        (1,45905,8437008,9,'AGUA MINERAL',NULL,'2022-01-01 00:00:00.000000',NULL,NULL),
        (2,16007,8480000,2,'COCACOLA',NULL,'2022-01-01 00:00:00.000000',NULL,NULL);